keys:
  - &host_atlas age190tmygg8xmn9tkj4yjgemvdd8s4tnmycr9n4qfrr0l97zxfq3gjs36xsn8
  - &host_enigma age1nleq0q2kzh2zn4pyr0dcy0zjnsr6sx8c5ttjahhfttkltsr2s3ksahhpkx
  - &host_nakulaptop age1m6gzjlvx5paan69evccl6kywj0ghdk46prumx4jn4hxcrxd4re6qckdl9w
  - &host_nomad age1y2f4jzfqjscgvwe3w3q8jmadtvxlsudk3c49lhqtdvatu7fwtdusez9fm9
  - &user_dave age1upzm9um3qljxlmxcg8vl35d7eyeqtnsfcnqlh3wtnj46dhfzwyrqa80avw
  - &user_ireen age1477n5xa2cr4tgdy80vxg24tsdcrcmzarn4ad99tjvrsjedq6sqpqsxyrms
  - &host_nucleus age197ewza8kky2gfef9d7qa464sylk0pshj4084hamxkhvtfyjgngfssjmxjc
  - &host_pulsar age1dgdwjmr80g6xgjtvfq6mkkwvd6wl8lusu45jxqe568dr49t5yfmslerynx
  - &host_pulsar age1yaqalu5ha0qt9nzupeh74xhnckx940ydeu7wrknmf7c5te0audhsfsldyw
  - &host_pulsar age1wphztg003pn0td9jglv4ywpk58k9g3ugvuus3wkq4y5fazgln47s9t8pxl
  - &host_pulsar age1puwtrw6npm87s9evyevws5rt5l9dvwugjz50r2kjnhsukvzpzpeqmssx50
  - &host_pulsar age1p8x8ghaacec3mzh8j5phe5yukvphdccwc54lpqea0c68f59vdqhq6d2fu7
creation_rules:
  - path_regex: hosts/common/secrets/.*
    key_groups:
      - age:
          - *host_atlas
          - *host_enigma
          - *host_nakulaptop
          - *host_nomad
          - *host_nucleus
          - *user_dave
          - *user_ireen
          - *host_pulsar
          - *host_pulsar
          - *host_pulsar
          - *host_pulsar
          - *host_pulsar
  - path_regex: users/secrets.yaml
    key_groups:
      - age:
          - *host_atlas
          - *host_enigma
          - *host_nakulaptop
          - *host_nomad
          - *host_nucleus
          - *user_dave
          - *user_ireen
          - *host_pulsar
          - *host_pulsar
          - *host_pulsar
          - *host_pulsar
          - *host_pulsar
  - path_regex: hosts/atlas/secrets/.*
    key_groups:
      - age:
          - *host_atlas
          - *user_dave
  - path_regex: hosts/enigma/secrets/.*
    key_groups:
      - age:
          - *host_enigma
          - *user_dave
  - path_regex: hosts/nakulaptop/secrets/.*
    key_groups:
      - age:
          - *host_nakulaptop
          - *user_dave
          - *user_ireen
  - path_regex: hosts/nomad/secrets/.*
    key_groups:
      - age:
          - *host_nomad
          - *user_dave
  - path_regex: hosts/nucleus/secrets/.*
    key_groups:
      - age:
          - *host_nucleus
          - *user_dave
  - path_regex: hosts/pulsar/secrets/.*
    key_groups:
      - age:
          - *host_pulsar
          - *host_nomad
          - *user_dave
          - *host_nomad
          - *user_dave
          - *host_nomad
          - *user_dave
          - *host_nomad
          - *user_dave
          - *host_nomad
          - *user_dave
  - path_regex: hosts/pulsar/secrets/.*
    key_groups:
      - age:
          - *host_pulsar
          - *host_nomad
          - *user_dave
          - *host_nomad
          - *user_dave
          - *host_nomad
          - *user_dave
          - *host_nomad
          - *user_dave
  - path_regex: hosts/pulsar/secrets/.*
    key_groups:
      - age:
          - *host_pulsar
          - *host_nomad
          - *user_dave
          - *host_nomad
          - *user_dave
          - *host_nomad
          - *user_dave
  - path_regex: hosts/pulsar/secrets/.*
    key_groups:
      - age:
          - *host_pulsar
          - *host_nomad
          - *user_dave
          - *host_nomad
          - *user_dave
  - path_regex: hosts/pulsar/secrets/.*
    key_groups:
      - age:
          - *host_pulsar
          - *host_nomad
          - *user_dave
