keys:
  - &host_atlas age190tmygg8xmn9tkj4yjgemvdd8s4tnmycr9n4qfrr0l97zxfq3gjs36xsn8
  - &host_beef age1wq5xj5mwv9xk4tp26cxc4xqjq9xd9hwqv0zeemawl2cc8sarmqesw366dh
  - &host_butcher age1nleq0q2kzh2zn4pyr0dcy0zjnsr6sx8c5ttjahhfttkltsr2s3ksahhpkx
  - &host_enigma age1nleq0q2kzh2zn4pyr0dcy0zjnsr6sx8c5ttjahhfttkltsr2s3ksahhpkx
  - &host_entropy age10r9fcpj4z6nc9p5n3e6eqdy9kkmvp0kafpj02qwyvwnhs3ev2pts8qawyt
  - &host_mirage age17pldhhyuahahzrtgcgfnrgse56mrjr2y5d52xy2glwu858hjtapsvug6sa
  - &host_nakulaptop age1m6gzjlvx5paan69evccl6kywj0ghdk46prumx4jn4hxcrxd4re6qckdl9w
  - &host_nomad age1y2f4jzfqjscgvwe3w3q8jmadtvxlsudk3c49lhqtdvatu7fwtdusez9fm9
  - &user_dave age1upzm9um3qljxlmxcg8vl35d7eyeqtnsfcnqlh3wtnj46dhfzwyrqa80avw
  - &user_ireen age1477n5xa2cr4tgdy80vxg24tsdcrcmzarn4ad99tjvrsjedq6sqpqsxyrms
  - &host_nucleus age197ewza8kky2gfef9d7qa464sylk0pshj4084hamxkhvtfyjgngfssjmxjc
creation_rules:
  - path_regex: hosts/common/secrets/.*
    key_groups:
      - age:
          - *host_atlas
          - *host_beef
          - *host_butcher
          - *host_entropy
          - *host_enigma
          - *host_mirage
          - *host_nakulaptop
          - *host_nomad
          - *user_dave
          - *user_ireen
          - *host_nucleus
  - path_regex: users/secrets.yaml
    key_groups:
      - age:
          - *host_atlas
          - *host_beef
          - *host_butcher
          - *host_enigma
          - *host_entropy
          - *host_mirage
          - *host_nakulaptop
          - *host_nomad
          - *user_dave
          - *host_nucleus
  - path_regex: hosts/atlas/secrets/.*
    key_groups:
      - age:
          - *host_atlas
          - *user_dave
  - path_regex: hosts/beef/secrets/.*
    key_groups:
      - age:
          - *host_beef
          - *user_dave
  - path_regex: hosts/butcher/secrets/.*
    key_groups:
      - age:
          - *host_butcher
          - *user_dave
  - path_regex: hosts/enigma/secrets/.*
    key_groups:
      - age:
          - *host_enigma
          - *user_dave
  - path_regex: hosts/entropy/secrets/.*
    key_groups:
      - age:
          - *host_entropy
          - *host_nomad
          - *user_dave
  - path_regex: hosts/mirage/secrets/.*
    key_groups:
      - age:
          - *host_nomad
          - *user_dave
          - *host_mirage
  - path_regex: hosts/nakulaptop/secrets/.*
    key_groups:
      - age:
          - *host_nakulaptop
          - *user_dave
          - *user_ireen
  - path_regex: hosts/nomad/secrets/.*
    key_groups:
      - age:
          - *host_nomad
          - *host_beef
          - *user_dave
  - path_regex: hosts/nucleus/secrets/.*
    key_groups:
      - age:
          - *host_nucleus
          - *host_nomad
          - *user_dave
          - *host_nomad
          - *user_dave
