keys:
  - &wsl_alex age1xmhmr66cem078nhlj2lp4g6xj0qqs57z5767k98qhqgpanatxaps6mclgs

creation_rules:
  - path_regex: hosts/sisyphos/secrets/.*
    key_groups:
      - age:
        - *wsl_alex
  - path_regex: hosts/hades/secrets/.*
    key_groups:
      - age:
        - *wsl_alex
  - path_regex: hosts/common/secrets/.*
    key_groups:
      - age:
          - *wsl_alex
  - path_regex: users/secrets.yaml
    key_groups:
      - age:
          - *wsl_alex
