# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/profiles/qemu-guest.nix")
    ];

  boot.initrd.availableKernelModules = [ "ahci" "xhci_pci" "virtio_pci" "virtio_scsi" "sr_mod" "virtio_blk" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];
  boot.kernelParams = [ "resume_offset=4503599627370495" ];
  boot.resumeDevice = "/dev/disk/by-uuid/558e1b77-4ddc-4080-82e7-ecfb4045a79d" ;

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/558e1b77-4ddc-4080-82e7-ecfb4045a79d";
      fsType = "btrfs";
      options = [ "subvol=root" ];
    };

  boot.initrd.luks.devices."pool0_0".device = "/dev/disk/by-uuid/4ab91d3d-a9e2-498d-a172-0e4223591ebf";

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/558e1b77-4ddc-4080-82e7-ecfb4045a79d";
      fsType = "btrfs";
      options = [ "subvol=home/active" ];
    };

  fileSystems."/home/.snapshots" =
    { device = "/dev/disk/by-uuid/558e1b77-4ddc-4080-82e7-ecfb4045a79d";
      fsType = "btrfs";
      options = [ "subvol=home/snapshots" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/558e1b77-4ddc-4080-82e7-ecfb4045a79d";
      fsType = "btrfs";
      options = [ "subvol=nix" ];
    };

  fileSystems."/persist" =
    { device = "/dev/disk/by-uuid/558e1b77-4ddc-4080-82e7-ecfb4045a79d";
      fsType = "btrfs";
      options = [ "subvol=persist/active" ];
      neededForBoot = true;
    };

  fileSystems."/persist/.snapshots" =
    { device = "/dev/disk/by-uuid/558e1b77-4ddc-4080-82e7-ecfb4045a79d";
      fsType = "btrfs";
      options = [ "subvol=persist/snapshots" ];
      neededForBoot = true;
    };

  fileSystems."/swap" =
    { device = "/dev/disk/by-uuid/558e1b77-4ddc-4080-82e7-ecfb4045a79d";
      fsType = "btrfs";
      options = [ "subvol=swap" ];
    };

  fileSystems."/var/local" =
    { device = "/dev/disk/by-uuid/558e1b77-4ddc-4080-82e7-ecfb4045a79d";
      fsType = "btrfs";
      options = [ "subvol=var_local/active" ];
    };

  fileSystems."/var/local/.snapshots" =
    { device = "/dev/disk/by-uuid/558e1b77-4ddc-4080-82e7-ecfb4045a79d";
      fsType = "btrfs";
      options = [ "subvol=var_local/snapshots" ];
    };

  fileSystems."/var/log" =
    { device = "/dev/disk/by-uuid/558e1b77-4ddc-4080-82e7-ecfb4045a79d";
      fsType = "btrfs";
      options = [ "subvol=var_log" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/CAE8-394C";
      fsType = "vfat";
    };

  swapDevices = [{
    device = "/swap/swapfile";
    size = (1024 * 4) + (1024 * 2); # RAM size + 2 GB
  }];


  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp1s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
